package com.lll.weidustore;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lll.weidustore.bean.ShopCar;
import com.lll.weidustore.bean.User;

import com.lll.weidustore.ShopCarDao;
import com.lll.weidustore.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopCarDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ShopCarDao shopCarDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopCarDaoConfig = daoConfigMap.get(ShopCarDao.class).clone();
        shopCarDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        shopCarDao = new ShopCarDao(shopCarDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ShopCar.class, shopCarDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        shopCarDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ShopCarDao getShopCarDao() {
        return shopCarDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
